Apply if/else suggestion

diff --git a/examples/with-docker/Dockerfile b/examples/with-docker/Dockerfile
--- a/examples/with-docker/Dockerfile
+++ b/examples/with-docker/Dockerfile
@@ -27,7 +27,12 @@ COPY . .
 # Uncomment the following line in case you want to disable telemetry during the build.
 # ENV NEXT_TELEMETRY_DISABLED 1
 
-RUN npm run build
+RUN \
+  if [ -f yarn.lock ]; then yarn run build; \
+  elif [ -f package-lock.json ]; then npm run build; \
+  elif [ -f pnpm-lock.yaml ]; then pnpm run build; \
+  else echo "Lockfile not found." && exit 1; \
+  fi
 
 # Production image, copy all the files and run next
 FROM base AS runner
